# Generated by Django 4.1.1 on 2022-10-13 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poblacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=50, verbose_name='estado')),
                ('a2020', models.IntegerField(verbose_name='2020')),
                ('a2010', models.IntegerField(verbose_name='2010')),
                ('a2000', models.IntegerField(verbose_name='2000')),
                ('a1990', models.IntegerField(verbose_name='1990')),
                ('a1980', models.IntegerField(verbose_name='1980')),
                ('a1970', models.IntegerField(verbose_name='1970')),
                ('a1960', models.IntegerField(verbose_name='1960')),
                ('a1950', models.IntegerField(verbose_name='1950')),
                ('a1940', models.IntegerField(verbose_name='1940')),
                ('a1930', models.IntegerField(verbose_name='1930')),
                ('a1920', models.IntegerField(verbose_name='1920')),
                ('a1910', models.IntegerField(verbose_name='1910')),
            ],
        ),
    ]
