# Generated by Django 4.1.1 on 2022-10-27 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PIB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=50, verbose_name='estado')),
                ('a2003', models.IntegerField(verbose_name='2003')),
                ('a2004', models.IntegerField(verbose_name='2004')),
                ('a2005', models.IntegerField(verbose_name='2005')),
                ('a2006', models.IntegerField(verbose_name='2006')),
                ('a2007', models.IntegerField(verbose_name='2007')),
                ('a2008', models.IntegerField(verbose_name='2008')),
                ('a2009', models.IntegerField(verbose_name='2009')),
                ('a2010', models.IntegerField(verbose_name='2010')),
                ('a2011', models.IntegerField(verbose_name='2011')),
                ('a2012', models.IntegerField(verbose_name='2012')),
                ('a2013', models.IntegerField(verbose_name='2013')),
                ('a2014', models.IntegerField(verbose_name='2014')),
                ('a2015', models.IntegerField(verbose_name='2015')),
                ('a2016', models.IntegerField(verbose_name='2016')),
                ('a2017', models.IntegerField(verbose_name='2017')),
                ('a2018', models.IntegerField(verbose_name='2018')),
                ('a2019', models.IntegerField(verbose_name='2019')),
                ('a2020', models.IntegerField(verbose_name='2020')),
            ],
        ),
    ]
