# Generated by Django 4.1.1 on 2022-10-27 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa1', '0002_pib'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pib',
            name='a2003',
            field=models.FloatField(verbose_name='2003'),
        ),
        migrations.AlterField(
            model_name='pib',
            name='a2004',
            field=models.FloatField(verbose_name='2004'),
        ),
        migrations.AlterField(
            model_name='pib',
            name='a2005',
            field=models.FloatField(verbose_name='2005'),
        ),
        migrations.AlterField(
            model_name='pib',
            name='a2006',
            field=models.FloatField(verbose_name='2006'),
        ),
        migrations.AlterField(
            model_name='pib',
            name='a2007',
            field=models.FloatField(verbose_name='2007'),
        ),
        migrations.AlterField(
            model_name='pib',
            name='a2008',
            field=models.FloatField(verbose_name='2008'),
        ),
        migrations.AlterField(
            model_name='pib',
            name='a2009',
            field=models.FloatField(verbose_name='2009'),
        ),
        migrations.AlterField(
            model_name='pib',
            name='a2010',
            field=models.FloatField(verbose_name='2010'),
        ),
        migrations.AlterField(
            model_name='pib',
            name='a2011',
            field=models.FloatField(verbose_name='2011'),
        ),
        migrations.AlterField(
            model_name='pib',
            name='a2012',
            field=models.FloatField(verbose_name='2012'),
        ),
        migrations.AlterField(
            model_name='pib',
            name='a2013',
            field=models.FloatField(verbose_name='2013'),
        ),
        migrations.AlterField(
            model_name='pib',
            name='a2014',
            field=models.FloatField(verbose_name='2014'),
        ),
        migrations.AlterField(
            model_name='pib',
            name='a2015',
            field=models.FloatField(verbose_name='2015'),
        ),
        migrations.AlterField(
            model_name='pib',
            name='a2016',
            field=models.FloatField(verbose_name='2016'),
        ),
        migrations.AlterField(
            model_name='pib',
            name='a2017',
            field=models.FloatField(verbose_name='2017'),
        ),
        migrations.AlterField(
            model_name='pib',
            name='a2018',
            field=models.FloatField(verbose_name='2018'),
        ),
        migrations.AlterField(
            model_name='pib',
            name='a2019',
            field=models.FloatField(verbose_name='2019'),
        ),
        migrations.AlterField(
            model_name='pib',
            name='a2020',
            field=models.FloatField(verbose_name='2020'),
        ),
    ]
