# Generated by Django 4.1.1 on 2022-11-10 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapa1', '0004_densidad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Densidad',
        ),
    ]
